const icons = {
  "SJ": null,
  "LC": null,
  "CC": null,
  "OR": null,
  "VR": "image",
  "ACT": "bowtie",
  "AGC": "leaf",
  "FADEU": "crop",
  "ART": "color-palette",
  "FIS": "",
  "astrofisica": "planet",
  "cara": "body",
  "ciencia política": "bookmark",
  "BIO": "bug",
  "CS": "medkit",
  "EA": "cash",
  "D": null,
  "COM": "chatbubbles",
  "CCL": "hammer",
  "DPT": "football",
  "DE": "briefcase",
  "DNO": "images",
  "EDU": "star",
  "ENF": "pulse",
  "URB": "pin",
  "EST": "rose",
  "FIL": "person",
  "FIS": "calculator",
  "GEO": "map",
  "HIS": "clock",
  "ING": "laptop",
  "LET": "book",
  "MAT": "cube",
  "MED": "thermometer",
  "MUS": "musical-note",
  "ODONT": "clipboard",
  "PSI": "help",
  "QIM": "beaker",
  "SOC": "people",
  "TTF": "egg",
  "TRSOC": "happy",
}

export default icons
